In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/customer_purchase_merchant_dataset_50000.csv')

In [4]:
df.head(3)

,customer_id,age,gender,income,product_category,browsing_time,pages_viewed,previous_purchases,discount_used,purchased
0,109721,56.0,Male,40702.27,Fashion,28.25,19.0,3.0,Yes,1
1,135306,22.0,Male,14907.71,Grocery,11.25,3.0,4.0,No,1
2,133033,43.0,Female,15860.81,Home,22.55,6.0,6.0,Yes,1

### To Correct Inconsistent values

In [ ]:
df['gender'].value_counts()

gender
Female     23642
Male       22865
Other       1437
FEMALE       445
male         422
X             52
Unknown       51
other         10
Name: count, dtype: int64

In [8]:
map_gender = {
    'Male' : 'Male',
    'Female':'Female',
    'FEMALE':'Female',
    'Other': 'Other',
    'male' :'Male',
    'other':'Other',
    'Unknown':'Unknown',
    'X':'Male'
}
df['gender'] = df['gender'].map(map_gender)

In [10]:
df['gender'].value_counts()

gender
Female     24087
Male       23339
Other       1447
Unknown       51
Name: count, dtype: int64

In [11]:
product_category_map = {
    'Fashion' :  'Fashion',
    'Grocery' :  'Grocery',
    'Home'    :   'Home',
    'Beauty'  :   'Beauty',
    'Electronics' :'Electronics',
    'Sports' : 'Sports',
    'electronics' :'Electronics',
    'grocery' :  'Grocery',
    'HOME' :     'Home',
    'FASHION' : 'Fashion',
    'SPORTS' :'Sports',
    'beauty' :  'Beauty'
} 
df['product_category']  = df['product_category'].map(product_category_map)

In [12]:
df['product_category'].value_counts()

product_category
Fashion        10745
Electronics     9951
Grocery         9794
Home            7329
Sports          6434
Beauty          4979
Name: count, dtype: int64

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(50000, 10)

In [15]:
df.head(3)

,customer_id,age,gender,income,product_category,browsing_time,pages_viewed,previous_purchases,discount_used,purchased
0,109721,56.0,Male,40702.27,Fashion,28.25,19.0,3.0,Yes,1
1,135306,22.0,Male,14907.71,Grocery,11.25,3.0,4.0,No,1
2,133033,43.0,Female,15860.81,Home,22.55,6.0,6.0,Yes,1

In [ ]:
df.to_csv("cleaned_data.csv")

### Conclusion:
The initial analysis shows that the dataset contains missing values, inconsistent data, and some incorrect data types. Since the missing values account for approximately 3% of the dataset, we will handle them through appropriate imputation techniques. We will also correct the inconsistent values and data types. After cleaning the data, we can perform an in-depth EDA and generate more reliable insights.